# Generated by Django 6.0 on 2026-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_status_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
